# Generated by Django 3.2.25 on 2024-03-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('merchant_id', models.IntegerField()),
                ('order_type', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], max_length=10)),
                ('item_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('non_taxable_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loyalty_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packing_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discounted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_completed_date', models.DateTimeField()),
            ],
        ),
    ]
