# Generated by Django 3.2.25 on 2024-03-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_alter_order_order_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
